version: 0.2
phases:
  build:
    commands:
      - zip ./lambda-code-v0.0.2.zip lambda_function.py slack_sdk/ -r
artifacts:
  files:
    - lambda-code-v0.0.2.zip
    - deployment.yml
  name: $AWS_REGION-$(date +%Y-%m-%d) 