version: 0.2
env:
  variables:
    - GHANIMIG_LAMBDA_CODE: $AWS_REGION-$(date +%Y-%m-%d)-$CODEBUILD_BUILD_NUMBER/lambda-code-v0.0.$CODEBUILD_BUILD_NUMBER.zip
  exported-variables:
    - GHANIMIG_LAMBDA_CODE
phases:
  pre_build:
    commands:
      - echo "Nothing in the pre-build phase."
  build:
    commands:
      - echo "Entering build phase. Will zip the lambda files and create a package."
      - zip ./lambda-code-v0.0.$CODEBUILD_BUILD_NUMBER.zip lambda_function.py slack_sdk/ -r
artifacts:
  files:
    - lambda-code-v0.0.$CODEBUILD_BUILD_NUMBER.zip
    - deployment.yml
    - appspec.yml
  name: $AWS_REGION-$(date +%Y-%m-%d)-$CODEBUILD_BUILD_NUMBER