version: 0.2
env:
  exported-variables:
    - GHANIMIG_LAMBDA_CODE
    - GHANIMIG_S3_PATH
phases:
  pre_build:
    commands:
      - echo "Nothing in the pre-build phase."
  build:
    commands:
      - echo "Entering build phase. Will zip the lambda files and create a package."
      - zip ./lambda-code-v0.0.$CODEBUILD_BUILD_NUMBER.zip lambda_function.py slack_sdk/ -r
      - export GHANIMIG_LAMBDA_CODE=lambda-code-v0.0.$CODEBUILD_BUILD_NUMBER.zip
artifacts:
  files:
    - lambda-code-v0.0.$CODEBUILD_BUILD_NUMBER.zip
    - deployment.yml
    - appspec.yml
    secondary-artifacts:
      LambdaArtifacts:
        base-directory: lambda-code
        files:
          - '**/*'