---
AWSTemplateFormatVersion: '2010-09-09'
Resources:

#| Resource                          | Type                    | Description                                      |
#|------------------------------     |-------------------------|--------------------------------------------------|
#| GetSecretValueLambdaPolicy        | AWS::IAM::ManagedPolicy | IAM policy with GetSecretValue value permissions |
#| CostAnomalyToSlackLambdaRole      | AWS::IAM::Role          | IAM Role associated with the Lambda Functions    |
#| DescribeAccountNameLambdaPolicy   | AWS::IAM::ManagedPolicy | IAM policy to DescribeAccount Name               |

 
  GetSecretValueLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          Resource: "*"
          Condition:
            StringEquals:
             'secretsmanager:SecretId': !Ref SlackWebhookURLSecret
      Roles:
      - Ref: CostAnomalyToSlackLambdaRole

  DescribeAccountNameLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: displayAccountNameEnabled
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - organizations:DescribeAccount
          Resource: "arn:aws:organizations::*:account/o-*/*"
      Roles:
      - Ref: CostAnomalyToSlackLambdaRole
      
  CostAnomalyToSlackLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Tags:
      - Key: Project
        Value: CostAnomalyToSlack


#| Resource            | Type            | Description                                                                     |
#|---------------------|-----------------|---------------------------------------------------------------------------------|
#| SnsTopicCostAnomaly | AWS::SNS::Topic | SNS Topic that shall receive notifications from Cost Explorer Anomaly Detection |

  SnsTopicCostAnomaly:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref CostAnomalyToSlackLambdaAliasProd
        Protocol: lambda
      Tags:
      - Key: Project
        Value: CostAnomalyToSlack
    DependsOn:
    - CostAnomalyToSlackLambda
  SnsTopicPolicyCostAnomaly:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument: 
        {
          "Statement": [
            {
            "Sid": "costalerts to publish",
            "Effect": "Allow",
            "Principal": { 
              "Service": "costalerts.amazonaws.com" 
              },
              "Action": "sns:Publish",
              "Resource": !Ref SnsTopicCostAnomaly
            },
            {
              "Sid": "Lambda to subscribe",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"

              },
              "Action": [
                "sns:Subscribe",
                "sns:Receive"
                ],
              "Resource": !Ref SnsTopicCostAnomaly,
              "Condition": {
                "StringEquals": {
                  "lambda:FunctionArn": !Ref CostAnomalyToSlackLambdaAliasProd
                }

              }
            }
            ]
        }
          
      Topics: 
      - !Ref SnsTopicCostAnomaly


#| Resource                              | Type                    | Description                                            |
#|---------------------------------------|-------------------------|--------------------------------------------------------|
#| CostAnomalyToSlackLambda              | AWS::Lambda::Function   | Main Lambda Function that will call Slack Webhooks API |
#| CostAnomalyToSlackLambdaSnsPermission | AWS::Lambda::Permission | Permission for SNS to invoke CostAnomalyToSlackLambda  |

  CostAnomalyToSlackLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: s3Bucket
        S3Key: !Ref codePackage
      Description: Lambda Function to Send Cost Anomaly Events to Slack Webhook
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
        - CostAnomalyToSlackLambdaRole
        - Arn
      Runtime: python3.7
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookURLSecret
      Tags:
      - Key: Project
        Value: CostAnomalyToSlack
  CostAnomalyToSlackLambdaVersion:
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    Properties: 
      FunctionName: !GetAtt CostAnomalyToSlackLambda.Arn
  CostAnomalyToSlackLambdaAliasProd:
    Type: AWS::Lambda::Alias
    Properties: 
      FunctionName: !GetAtt CostAnomalyToSlackLambda.Arn
      FunctionVersion: !GetAtt CostAnomalyToSlackLambdaVersion.Version
      Name: prod
  CostAnomalyToSlackLambdaSnsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: SnsTopicCostAnomaly
      FunctionName: !Ref CostAnomalyToSlackLambdaAliasProd

#| Resource              | Type                        | Description                            |
#|-----------------------|-----------------------------|----------------------------------------|
#| SlackWebhookURLSecret | AWS::SecretsManager::Secret | Secret storing the Slack webhook URL.  |
  
  SlackWebhookURLSecret:        
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: !Join [ "-", [ !Ref AWS::StackName, anomaly-detection-slack-webhook-url ] ] 
      SecretString: !Sub
      - '{"anomaly-detection-slack-webhook-url": "${secret}"}'
      - { secret: !Ref slackWebhookURL }  
      Tags: 
      - Key: Project
        Value: CostAnomalyToSlack

  CostAnomlayToSlackApplication:
    Type: AWS::AppConfig::Application
    Properties: 
      Description: Cost Anomaly to Slack AppConfig Application
      Name: cost-anomaly-to-slack-application
      Tags: 
      - Key: Project
        Value: CostAnomalyToSlack

  CostAnomalyToSlackgEnvironment:
    Type: AWS::AppConfig::Environment
    Properties: 
      ApplicationId: !Ref CostAnomlayToSlackApplication
      Name: cost-anomaly-to-slack-environment
      Description: Cost Anomaly to Slack AppConfig Application Environment
      Tags: 
      - Key: Project
        Value: CostAnomalyToSlack

  CostAnomalyToSlackConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties: 
      ApplicationId: !Ref CostAnomlayToSlackApplication
      Name: cost-anomaly-to-slack-configuration-profile
      Description: Cost Anomaly to Slack AppConfig Application Environment
      LocationUri: hosted
      Tags: 
      - Key: Project
        Value: CostAnomalyToSlack
       
  CostAnomalyToSlackConfigVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref CostAnomlayToSlackApplication
      ConfigurationProfileId: !Ref CostAnomalyToSlackConfigProfile
      Description: 'A sample hosted configuration version'
      Content: !Sub 
      - '{"feature-flags": {"displayAccountName": ${displayAccountNameValueBoolean}}}'
      - displayAccountNameValueBoolean: !Ref displayAccountName
      ContentType: 'application/json'

  CostAnomalyToSlackDeploymemtStrategy:    
    Type: AWS::AppConfig::DeploymentStrategy
    Properties: 
      Name: cost-anomaly-to-slack-deployment-strategy
      Description: Cost Anomaly to Slack Deployment Strategy
      DeploymentDurationInMinutes: 1
      FinalBakeTimeInMinutes: 1
      GrowthFactor: 100
      GrowthType: LINEAR
      ReplicateTo: NONE
      Tags: 
      - Key: Project
        Value: CostAnomalyToSlack
  
  CostAnomalyToSlackDeploymemt:      
    Type: AWS::AppConfig::Deployment
    Properties: 
      ApplicationId: !Ref CostAnomlayToSlackApplication
      ConfigurationProfileId: !Ref CostAnomalyToSlackConfigProfile
      ConfigurationVersion: !Ref CostAnomalyToSlackConfigVersion
      DeploymentStrategyId: !Ref CostAnomalyToSlackDeploymemtStrategy
      Description: Cost Anomaly to Slack Deployment
      EnvironmentId: !Ref CostAnomalyToSlackgEnvironment
      Tags: 
      - Key: Project
        Value: CostAnomalyToSlack
    
#| Parameter       | Type   | Description                                                                                               |
#|-----------------|--------|-----------------------------------------------------------------------------------------------------------|
#| s3Bucket        | String | S3 bucket where the Lambda code package is stored                                                         |
#| codePackage     | String | The code package S3 object key name. Typically, filename.zip                                              |
#| slackWebhookURL | String | Slack channel webhook URL. If you don't have one already, check https://api.slack.com/messaging/webhooks. |

Parameters:
  sourceAccount:
    Type: String
    Description: Enter the 11-digit AWS Account Number of the cost anomaly notification subscription. If you would like to aggregate data across all of your accounts, enter the Payer/Management account number. Else, if you would like to receive notifications of a specific member account (be it this account), enter the account number. 
  s3Bucket:
    Type: String
    Description: S3 Bucket where your Lambda functions and StepFunctions state machines    are stored.
  codePackage:
    Type: String
    Description: S3 key for the Lambda Code. 
  slackWebhookURL:
    Type: String
    Description: Slack Webhook URL.
  displayAccountName:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Select whether to display Account Name in the Slack Notification or not. This will require special permissions for the Lambda function to access the Organisations API.

Conditions:
  displayAccountNameEnabled: !Equals 
    - !Ref displayAccountName
    - true

Outputs:
  snsTopicArn:
    Description: The Arn of the SNS topic created by the stack. This topic Arn is to be configured in the Anomaly Detection Subscription Configuratios.  
    Value: !Ref SnsTopicCostAnomaly
  
